package it.giacomos.android.osmer;

public enum StringType {
	TODAY, TOMORROW, TWODAYS, HOME,
	LATEST_MIN_TEMP, LATEST_MAX_TEMP, LATEST_HUMIDITY,
	LATEST_RAIN, LATEST_WIND, LATEST_PRESSURE, LATEST_SEA, LATEST_SNOW,
	LATEST_TABLE,
	DAILY_MIN_TEMP, DAILY_MAX_TEMP, DAILY_HUMIDITY,
	DAILY_RAIN, DAILY_WIND, DAILY_PRESSURE, DAILY_SEA, DAILY_SNOW,
	DAILY_TABLE,
	WEBCAMLIST_OSMER, WEBCAMLIST_OTHER
}
